# Generated by Django 2.1.4 on 2019-02-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_material',
            name='material_quantity',
            field=models.CharField(max_length=100),
        ),
    ]
