# Generated by Django 2.1.4 on 2019-02-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190223_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_price', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_order', to='polls.User_info')),
            ],
        ),
        migrations.AddField(
            model_name='food_info',
            name='food_intro_text',
            field=models.CharField(default='No introduction', max_length=10000),
        ),
        migrations.AddField(
            model_name='food_info',
            name='food_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food_info',
            name='food_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Food_info'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell_order', to='polls.User_info'),
        ),
    ]
