# Generated by Django 2.1.4 on 2019-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190224_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_price',
            field=models.FloatField(default=0),
        ),
    ]
