# Generated by Django 2.1.4 on 2019-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190224_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='address',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_num',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
