# Generated by Django 2.1.4 on 2019-02-24 08:26

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_user_info_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(default='', upload_to=polls.models.user_path),
        ),
    ]
