# Generated by Django 2.1.4 on 2019-02-24 09:34

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_food_info_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_info',
            name='img',
        ),
        migrations.AddField(
            model_name='food_info',
            name='food_img',
            field=models.ImageField(default='', upload_to=polls.models.food_path),
        ),
    ]
