# Generated by Django 2.1.4 on 2019-02-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190224_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='food_img',
            field=models.ImageField(default='', upload_to='food'),
        ),
    ]
